### ISSUE TITLE
Unable to decorate with multiple config elements

### ISSUE THREAD

**Issue by JoeyJoJoJrShabadu** [mjdorma/funconf#1]
When decorating a function using multiple config elements a TypeError('too many positional arguments') is raised.

This can be reproduced using the 'demo.conf' in the documentation with the following code.

<pre><code>
import begin
import funconf

config = funconf.Config('demo.conf')

@begin.subcommand
@config.foo
@config.bread
def foo(**k):
    "This is the foo code"
    print("Foo got %s" % k)
    print("Config is:")
    print(config)

@begin.start
def entry():
    "This is a super dooper program..."
    pass
</code></pre>

The following traceback is produced:

<pre>Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    @begin.start
  File "C:\Anaconda\lib\site-packages\begin\main.py", line 135, in start
    return _start(func)
  File "C:\Anaconda\lib\site-packages\begin\main.py", line 117, in _start
    prog.start()
  File "C:\Anaconda\lib\site-packages\begin\main.py", line 55, in start
    opts, sub_group=self._group, collector=self._collector)
  File "C:\Anaconda\lib\site-packages\begin\cmdline.py", line 237, in apply_opti
ons
    return_value = call_function(subfunc, signature(subfunc), opts)
  File "C:\Anaconda\lib\site-packages\begin\cmdline.py", line 217, in call_funct
ion
    return func(*pargs, **kwargs)
  File "C:\Anaconda\lib\site-packages\funconf.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\funconf.py", line 248, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\funconf.py", line 379, in wrapper
    arguments = OrderedDict(sig.bind(*args, **kwargs).arguments)
  File "C:\Anaconda\lib\site-packages\funcsigs\__init__.py", line 771, in bind
    return self._bind(args, kwargs)
  File "C:\Anaconda\lib\site-packages\funcsigs\__init__.py", line 707, in _bind
    raise TypeError('too many positional arguments')
TypeError: too many positional arguments
</pre>

Running a -h runs without error

**Comment by mjdorma** [comment]
At first I thought this was a bug.  After drilling into it, I did a full 180.  It boils down to what I'd expect to get out of the Python function protocol.  

If I were to do the following:

```
def foo(**k):
    pass

foo(4)
```

I'd get a TypeError. This is what appears to be happening in the above example.  I did experiment with options on how to cast between positional keywords and keyword only args, but things quickly got ugly and I ended up breaking everything.

Decorating multiple times will work if the definition of the decorated function will accept the arguments.

If you think this is still a bug, please reopen the issue and let me know how and where I'm wrong (I floundered for some time on this one... and it took me a bit to come to grips with and show why my initial position was incorrect).
